### ISSUE TITLE
searchFormSchema内定义一个solt 如何在BasicTable展示 ？

### ISSUE THREAD

**Issue by zsl1549** [dromara/lamp-cloud#232]
# 版本信息：
JDK 版本(必填) : 1.8.0
源码版本(必填)：lamp-web-plus
MySQL(必填)： 5.7.9

求大佬指导一下  BasicTable里有BasicForm 就可以显示，如何在BasicTable里直接写呢？

![image](https://user-images.githubusercontent.com/32888522/205494251-f61e0175-95f6-4581-a1ce-501131424a60.png)

**Comment by zuihou** [comment]
![Uploading image.png…]()
试试 form- 前缀

**Comment by zsl1549** [comment]
谢谢大神指点 谢谢
