### ISSUE TITLE
BasicTable columns内容多 表头和内容没有对齐

### ISSUE THREAD

**Issue by zsl1549** [dromara/lamp-cloud#233]
![image](https://user-images.githubusercontent.com/32888522/205604029-16248a5e-02ce-45a9-9cc7-d2d6247fab6e.png)

**Comment by zuihou** [comment]
![image](https://user-images.githubusercontent.com/8500410/205607311-fdfedd69-e412-4951-8278-5667faefca9a.png)

看下是不是这里引起的

**Comment by zsl1549** [comment]
![image](https://user-images.githubusercontent.com/32888522/205609852-54849ffb-7bcb-444a-86af-03515c37ebf4.png)
不是这里引起的 值都试过了 还是不行

**Comment by zsl1549** [comment]
@zuihou 请大佬指点一下  这个样式问题好恶心啊

**Comment by zsl1549** [comment]
休息大佬指点 还是解决不了我在研究下
