### ISSUE TITLE
验证码接口404

### ISSUE THREAD

**Issue by W9696W** [dromara/lamp-cloud#237]
# 版本信息：
JDK 版本(必填) : 1.8.0
源码版本(必填)：4.x   lamp-cloud-pro-datasource-column 
MySQL(必填)： 8.0.26
Nacos(必填)：2.0.3
前端lamp-web-pro

# 问题描述：
后端，nginx部署在docker上，前端打包后直接把dist文件放在nginx挂载的HTML目录里。
nginx配置截图
![image](https://user-images.githubusercontent.com/108283095/220503961-9938f5aa-59db-45de-983c-db86b7354c3b.png)

# 报错截图
![image](https://user-images.githubusercontent.com/108283095/220503389-daa93d43-d90a-4533-941b-8bf9698f0824.png)
![image](https://user-images.githubusercontent.com/108283095/220503530-1b6c4ac3-64ea-4b7d-a8c6-6316b7430c32.png)

# 重现步骤
1. 访问了什么接口？
2. 传递什么参数？
3. 后端控制台报了什么错？
4. 前端控制台报了什么错？

# 支持一下
如果该issue帮助了你, 麻烦给项目点个star, 并给当前issue回复一下 “👍” 或者 “已解决”.

**Comment by zuihou** [comment]
nginx 配错了

**Comment by zuihou** [comment]
参考： 
<img width="1184" alt="image" src="https://user-images.githubusercontent.com/8500410/220509384-db29fbf8-244c-4dd8-94f2-56fd4bafbda7.png">

**Comment by W9696W** [comment]
可是我改了之后又出现新的错误，以下为改后的配置和报错截图。






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dromara/lamp-cloud"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月22日(星期三) 上午10:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dromara/lamp-cloud] 验证码接口404 (Issue #237)





 
参考：

**Comment by zuihou** [comment]
1. nginx 代理的是 lamp-gateway的ip和端口 
2. 直接访问 lamp-gateway 的ip+port + 第二个图中的获取验证码的地址 ，确保能正常访问

**Comment by zuihou** [comment]
如：
这个地址是通过nginx访问的， 

https://datasource.tangyh.top/api/oauth/anyTenant/captcha?key=E4BA9375ECB06368AEB36B901677040090711&_t=1677040092478


这个地址是直接访问lamp-gateway的（这个地址一般内网ip即可，但验证的时候，想法用外网ip，验证成功后，只保留内网ip访问）
https://gatewayip:port/api/oauth/anyTenant/captcha?key=E4BA9375ECB06368AEB36B901677040090711&_t=1677040092478



确保2个地址都能正常访问

**Comment by W9696W** [comment]
docker上的gateway容器通过端口映射可以通过服务器访问，但我这两个地址都仍然不能访问。

**Comment by zuihou** [comment]
那就是docker 端口没映射出来吧

**Comment by W9696W** [comment]
嗯嗯，已经解决



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月22日(周三) 下午5:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [dromara/lamp-cloud] 验证码接口404 (Issue #237)




 
那就是docker 端口没映射出来吧
