### ISSUE TITLE
lamp-cloud如何同时插入三张表的数据

### ISSUE THREAD

**Issue by zhangrui2023** [dromara/lamp-cloud#239]
# 版本信息：
JDK 版本(必填) : 1.8.0
源码版本(必填)：4.x
MySQL(必填)： 8.0.15
Nacos(必填)：2.0.3

# 问题描述：
新增页面的字段包含了三张表的字段，我要给三张表同时新增三条数据，但是在Controller里只能插入一个表的数据
因为每个Controller都继承了SuperController，也就是一个Controller代表一个实体，如何给另外两张表插入前端传过来的数据

# 报错截图
![image](https://user-images.githubusercontent.com/126763006/222376405-636600b2-43c2-4691-a221-458199fc6f50.png)
![image](https://user-images.githubusercontent.com/126763006/222376534-2e876a8a-553c-46ee-a681-34586e8d8fd8.png)

# 重现步骤
1. 访问了什么接口？
2. 传递什么参数？
3. 后端控制台报了什么错？
4. 前端控制台报了什么错？

# 支持一下
如果该issue帮助了你, 麻烦给项目点个star, 并给当前issue回复一下 “👍” 或者 “已解决”.

**Comment by zuihou** [comment]
AController 调用 AService，  AService 可以调用任意 B、C、DService
