### ISSUE TITLE
企业版lamp-web-pro 4.13.0启动后访问报错

### ISSUE THREAD

**Issue by 1966034115** [dromara/lamp-cloud#278]
# 版本信息：
nodejs 20.0.0、nodejs 18+

# 问题描述：
拉取gitlab上最新的lamp-web-pro的项目，不做任何修改，安装依赖后执行“npm run dev:column”可以正常启动，但是访问首页报错。

# 报错截图
![image](https://user-images.githubusercontent.com/54665014/234460588-774a2c9e-a559-4070-a42e-8ae1fab6bad6.png)
![image](https://user-images.githubusercontent.com/54665014/234460661-bad60669-f113-4bce-9270-6b0d99731e24.png)

# 重现步骤
拉取gitlab上最新的lamp-web-pro的项目，不做任何修改，安装依赖后执行“npm run dev:column”，访问“localhost:3100”

**Comment by zuihou** [comment]
1. rm -rf node_modules
2. rm -rf pnpm-lock.yaml
2 重新 pnpm install
