### ISSUE TITLE
lamp-boot-pro-datasource-column版本 登录日志和操作日志没有起作用

### ISSUE THREAD

**Issue by AmyZurich** [dromara/lamp-cloud#281]
# 版本信息：
JDK 版本(必填) : 1.8.0
源码版本(必填)：
MySQL(必填)： 5.7.9
Nacos(必填)：

# 问题描述：

# 报错截图

# 重现步骤
1. 访问了什么接口？
2. 传递什么参数？
3. 后端控制台报了什么错？
4. 前端控制台报了什么错？

# 支持一下
如果该issue帮助了你, 麻烦给项目点个star, 并给当前issue回复一下 “👍” 或者 “已解决”.

**Comment by AmyZurich** [comment]
我登录的时候，和操作的时候，登录日志表和操作日志表里面并没有插入数据，我除了改了mysql的配置以外，其他代码都没有改动

**Comment by zuihou** [comment]
有bug，等会更新代码
