### ISSUE TITLE
ApiSelect 

### ISSUE THREAD

**Issue by Angle-bo** [dromara/lamp-cloud#289]
# 版本信息：
lamp-web-pro build: 4.13.1 

# 问题描述：
ApiSelect onChange 事件回调值丢失

# 报错截图
lamp-web-pro截图如下：
![lamp-pro](https://github.com/dromara/lamp-cloud/assets/16486675/584a7c77-537f-4d10-b7a6-fb72c4c62d9d)

[vue-vben-admin]截图如下：
![vbean](https://github.com/dromara/lamp-cloud/assets/16486675/7a5082f1-19e0-4b9c-bec6-ac2adc040083)

# 重现步骤
进入页面，第一次变更Select选项时，change数据丢失。
vben-admin中没发现这个问题。

# 支持一下
如果该issue帮助了你, 麻烦给项目点个star, 并给当前issue回复一下 “👍” 或者 “已解决”.

**Comment by Angle-bo** [comment]
第二次切换Select选项时，onChange数据不对。
应该是ApiSelect====>: 3 {label: '选项3', value: '3'}
但是控制台输出：
![image](https://github.com/dromara/lamp-cloud/assets/16486675/98ea1191-b517-4f28-93c9-fa4dbf7cf398)

**Comment by zuihou** [comment]
useFormItem.ts 中 ` nextTick(() => { }) ;` 被我注释了, 原因是之前的版本 不管加不加 nextTick 都有bug。

加上 nextTick 后，目前简单测试了能解决你提的问题和我之前发现的问题。 你可以试试，发现有什么其他问题及时反馈。我也多调试调试

```
      nextTick(() => {
        emit?.(changeEvent, value, ...(toRaw(unref(emitData)) || []));
      });
```

**Comment by zuihou** [comment]
因为之前发现加你 nextTick 还会影响 ApiTree和ApiRadioGroup

**Comment by Angle-bo** [comment]
好的，我再看看，因为我别的地方有用ApiTree和ApiRadioGroup。所以还不能简单的放开nextTick(() => { }) ;

**Comment by zuihou** [comment]
刚测试 加上 nextTick， ApiRadioGroup 和 ApiSelect 都没问题了。

**Comment by Angle-bo** [comment]
加上 nextTick会导致第一次，数据校验报错
临时解决办法：

1. onOptionsChange获取到Select所有选项，进行存储

2. 在onChange事件中通过获取的value，去存储的所有选项中找到对应的完整对象
