### ISSUE TITLE
租户维护：租户已经过了有效期，租户管理员还可以继续登录。

### ISSUE THREAD

**Issue by qixiangcheng12** [dromara/lamp-cloud#296]
# 版本信息：lamp-boot-server-column
JDK 版本(必填) : 1.8.0
源码版本(必填)：4.14.1
MySQL(必填)： 5.7.9
Nacos(必填)：

# 问题描述：
租户维护：租户已经过了有效期，租户管理员还可以继续登录。

# 报错截图
![image](https://github.com/dromara/lamp-cloud/assets/141601430/7a311595-9931-45b1-a455-fd5e8c4d40e0)

![image](https://github.com/dromara/lamp-cloud/assets/141601430/9285d76c-b389-46f5-9ca9-257ea6effc3b)

# 重现步骤
1. 访问了什么接口？
2. 传递什么参数？
3. 后端控制台报了什么错？
4. 前端控制台报了什么错？

# 支持一下
如果该issue帮助了你, 麻烦给项目点个star, 并给当前issue回复一下 “👍” 或者 “已解决”.

**Comment by zuihou** [comment]
这个逻辑确实没有加，下个版本加一下

**Comment by zuihou** [comment]
[9943455981d2bf43a7e471bc7f96a933bbc3d21c](http://git.tangyh.top/zuihou/lamp-cloud-pro-datasource-column/commit/9943455981d2bf43a7e471bc7f96a933bbc3d21c)  


下个版本同步代码
