### ISSUE TITLE
邮箱问题

### ISSUE THREAD

**Issue by nizpxox** [dromara/lamp-cloud#297]
# 版本信息：
JDK 版本(必填) : 1.8.0
源码版本(必填)：就是你现在文档得版本https://datasource.tangyh.top/#/home/welcome
MySQL(必填)： 5.7.9
Nacos(必填)：
nacos都注册上了，版本跟你文档推荐得一样

# 问题描述：
注册邮箱 注册邮箱账号失败
我这里面应该怎么配置，就是邮箱模板

# 报错截图
![image](https://github.com/dromara/lamp-cloud/assets/141626156/d411c611-0828-41dc-be6c-da5c13aceeaa)
![image](https://github.com/dromara/lamp-cloud/assets/141626156/c0e40679-c796-45f6-b075-7e053753b001)

# 重现步骤
代码没动，直接部署到服务器上
BizException: Sending the email to the following server failed : smtp.139.com:25

# 支持一下
如果该issue帮助了你, 麻烦给项目点个star, 并给当前issue回复一下 “👍” 或者 “已解决”.

**Comment by zuihou** [comment]
要在"接口管理” 配置正确的 接口参数
