### ISSUE TITLE
将本地的nacos 切换到远程服务器  启动报错

### ISSUE THREAD

**Issue by yongqiangipone** [dromara/lamp-cloud#305]
# 版本信息：
JDK 版本(必填) : 1.8.0
源码版本(必填)：4.0
MySQL(必填)： 5.7.9
Nacos(必填)：2.1.1

# 问题描述：
修改了nacos 地址 将本地的nacos 修改成远程服务器的。 暴露端口改为 23908 

# 报错截图
[
![_cgi-bin_mmwebwx-bin_webwxgetmsgimg__ MsgID=6424632986534011493 skey=@crypt_86c7be90_bb851acd1d951223203d2840ae54fada mmweb_appid=wx_webfilehelper](https://github.com/dromara/lamp-cloud/assets/10264936/8801e186-bcf9-461a-baa8-376b834e23c0)
![_cgi-bin_mmwebwx-bin_webwxgetmsgimg__ MsgID=3418975471714808862 skey=@crypt_86c7be90_bb851acd1d951223203d2840ae54fada mmweb_appid=wx_webfilehelper](https://github.com/dromara/lamp-cloud/assets/10264936/a95dab48-2040-40ce-a414-8db846885a21)
](url)

# 重现步骤
1. 访问了什么接口？
2. 传递什么参数？
3. 后端控制台报了什么错？
4. 前端控制台报了什么错？

# 支持一下
如果该issue帮助了你, 麻烦给项目点个star, 并给当前issue回复一下 “👍” 或者 “已解决”.

**Comment by zuihou** [comment]
若本地nacos可以，远程nacos不行，请检查远程nacos的4个端口可用性。

**Comment by yongqiangipone** [comment]
端口我都映射了。 项目中除了8848 配置 还有那些地方要把其他三个端口配置上吗？

**Comment by zuihou** [comment]
https://github.com/dromara/lamp-cloud/discussions/49

<img width="702" alt="image" src="https://github.com/dromara/lamp-cloud/assets/8500410/395496a3-51b9-4f53-9453-6dd4472b8837">

**Comment by yongqiangipone** [comment]
[](url)
![Uploading _cgi-bin_mmwebwx-bin_webwxgetmsgimg__&MsgID=1484941894501458988&skey=@crypt_86c7be90_082ff448d0789ee39a8cca1a3ae98deb&mmweb_appid=wx_webfilehelper.jpg…]()

**Comment by yongqiangipone** [comment]
![_cgi-bin_mmwebwx-bin_webwxgetmsgimg__ MsgID=1484941894501458988 skey=@crypt_86c7be90_082ff448d0789ee39a8cca1a3ae98deb mmweb_appid=wx_webfilehelper](https://github.com/dromara/lamp-cloud/assets/10264936/3957ddb0-27f0-43d4-bba8-7df11edde424)

请问这个错误是什么原因呀！ 找不到答案了。

**Comment by zuihou** [comment]
<img width="958" alt="image" src="https://github.com/dromara/lamp-cloud/assets/8500410/606e05da-41a8-478b-ab64-f9bc274c88b5">
检查 okhtp3 版本
