### ISSUE TITLE
docker 构建插件一键生成镜像或者一键部署到centos

### ISSUE THREAD

**Issue by niufwshd** [dromara/lamp-cloud#313]
# 版本信息：
JDK 版本(必填) : 1.8.0
源码版本(必填)：
MySQL(必填)： 5.7.9
Nacos(必填)：

# 问题描述：

 你好，看了文档中的部署步骤，大侠有意向优化父子pom来一键生成所有镜像么或者彻底能增加一键部署到服务器的脚本及文件。谢谢！
# 报错截图

# 重现步骤
1. 访问了什么接口？
2. 传递什么参数？
3. 后端控制台报了什么错？
4. 前端控制台报了什么错？

# 支持一下
如果该issue帮助了你, 麻烦给项目点个star, 并给当前issue回复一下 “👍” 或者 “已解决”.

**Comment by zuihou** [comment]
暂无计划哦。
