### ISSUE TITLE
使用gateway后性能无法提升

### ISSUE THREAD

**Issue by wanglin0612** [dromara/lamp-cloud#317]
# 版本信息：
JDK 版本(必填) : 1.8.0
源码版本(必填)：4.12.5
MySQL(必填)： 5.7.9
Nacos(必填)：2.04

# 问题描述：
使用jmeter压测服务，并发300-800，吞吐量一直在700-750左右，当跳过gateway直接压测底层服务，并发300-1000，吞吐量为3000左右，查看日志发现gateway执行完fiter转发请求到服务时中间耗时将近1秒。

# 报错截图

**Comment by wanglin0612** [comment]
gateway服务cpu一直在50%-60%之间

**Comment by zuihou** [comment]
因为 gateway-server  的 AuthenticationFilter 过滤器会对校验用户是否有某个uri接口的访问权限

**Comment by wanglin0612** [comment]
在所有filter执行完之后，转发到服务的时候很慢，不是filter慢-------- 原始邮件 --------发件人： 最后 ***@***.***>日期： 2023年10月13日周五 18:53收件人： dromara/lamp-cloud ***@***.***>抄送： wanglin0612 ***@***.***>, Author ***@***.***>主    题： Re: [dromara/lamp-cloud] 使用gateway后性能无法提升 (Issue #317)
因为 gateway-server  的 AuthenticationFilter 过滤器会对校验用户是否有某个uri接口的访问权限

**Comment by zuihou** [comment]
这种情况，你就得去给gateway调优了， gateway 转发是基于 openfeign  （实际就是http请求）的，性能可能会有影响，就看你们的接受程度。
