### ISSUE TITLE
[技术咨询] 如何集成多个数据库？

### ISSUE THREAD

**Issue by pinkcao** [dromara/lamp-cloud#319]
# 版本信息：
JDK 版本(必填) : 11
源码版本(必填)：lamp-cloud-pro-datasource-column 4.14.0
MySQL(必填)： 8.0.11
Nacos(必填)：2.0.2

# 问题描述：
在业务中遇到一个这样的需求：在一个服务中需要既访问mysql又访问sqlServer表，如果我想在一个服务中同时集成多个数据库，比如sqlServer与mysql同时集成，然后通过注解的方式切换数据源，应该怎么做？
目前仅做过以下尝试：
![image](https://github.com/dromara/lamp-cloud/assets/36530450/9d88a5d6-0a83-4702-8f08-8c6919971170)

![image](https://github.com/dromara/lamp-cloud/assets/36530450/1d874372-3951-49d4-8fa0-c835cdc7a848)

即在spring配置中加入了一个额外的数据源

报错如下：
![image](https://github.com/dromara/lamp-cloud/assets/36530450/adf14a7e-4611-4291-87bc-35eed97bf39e)

我的感觉可能仅通过修改database.yml的配置难以解决这个问题，因此想来咨询一下有没有相关的解决方案？

# 支持一下
如果该issue帮助了你, 麻烦给项目点个star, 并给当前issue回复一下 “👍” 或者 “已解决”.

**Comment by zuihou** [comment]
报错是： 缺少驱动， 在pom里面加 sqlserver的依赖。

配置没毛病，但这样配了之后，sqlserver的数据源是“死的”，即不能实现动态切换效果。

```
@DS("1")  // 查 yml中配置的 sqlserver
public class UserServiceImpl {
   ......
}

@DS("0")  // 查  yml中配置的  mysql
public class UserServiceImpl {
   ......
}

@DS("#thead.lamp_base")  // 查 动态租户库
public class UserServiceImpl {
   ......
}
```
